apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-project
  namespace: uat
  labels:
    app: basic-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basic-project
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: basic-project
    spec:
      containers:
      - name: basic-project
        image: arivu007/basic-project:v1.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: APP_ENV
          value: "UAT"
        - name: NODE_ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 3
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
