apiVersion: v1
kind: Service
metadata:
  name: basic-project-service
  labels:
    app: basic-project
spec:
  type: NodePort
  selector:
    app: basic-project
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
